source 'https://github.com/CocoaPods/Specs.git'

target 'DGSAttributedStringSuite', :exclusive => true do
  pod "DGSAttributedStringSuite", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "DGSAttributedStringSuite", :path => "../"

  
end
